export const BASE_TEST_COLUM_NAMES = [
  'CPF',
  'PRIVATE',
  'INCOMPLETO',
  'DATA DA ÚLTIMA COMPRA',
  'TICKET MÉDIO',
  'TICKET DA ÚLTIMA COMPRA',
  'LOJA MAIS FREQUÊNTE',
  'LOJA DA ÚLTIMA COMPRA',
];
